sonar.projectKey=eks-fastapi-devops-portfolio
sonar.projectName=EKS FastAPI DevOps Portfolio
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml

# exclude venv, cache, and compiled files from analysis
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc,**/tests/**
sonar.test.inclusions=**/tests/**
